[build]
  publish = "dist/"

  command = "npm run generate"

[[plugins]]
  package = "netlify-plugin-algolia-index"
    [plugins.inputs]
      exclude = ['/private', '/200', '/search']

[[plugins]]
  package = "netlify-plugin-opensearch"
    [plugins.inputs]
      siteShortName = "Demo Site"
      siteDescription = "Find stuff on the demo site"
      siteTags = "demos"
      siteContact = "luke@lukeoliff.com"
